name: testmain
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - .github/workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: create asset
      run: |
          echo ::set-env name=registryname::$(date +%s)
          echo "$(date +%s)"
          az ml registry create -f resources/registry/registry.yml -n $(date +%s)
